ci:
  autofix_commit_msg: |
    chore[pre-commit.ci]: auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_commit_msg: 'chore[pre-commit.ci]: pre-commit autoupdate'
  autoupdate_schedule: monthly

exclude: \.(out|log|h)$

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
    args: [--maxkb=1024]
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.270
  hooks:
  - id: ruff
    args: [--fix]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.9.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.4
  hooks:
  - id: clang-format
